accounts/urls.py
from django.urls import path
from accounts.views import Register, Login, Logout

app_name = 'accounts'

urlpatterns = [
    path("register/", Register.as_view(), name="register"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
]

products/urls.py
from django.urls import path
from products.views.views_func import (
    create_product,
    list_products,
    product_detail,
    product_delete,
    product_update,
)
from products.views.views_class import (
    ListProductView,
    CreatProductView,
    ProductListView,
    ProductCreateView,
    ProductDetailView,
    ProductUpdateView,
    ProductDeleteView
)
from products.views.api import products

app_name = 'products'

urlpatterns = [
    path("", list_products, name="list"),
    path("create/", ProductCreateView.as_view(), name="create"),
    path("detail/<int:prod_id>/",
         product_detail, name="detail"),
    path("delete/<int:prod_id>", ProductDeleteView.as_view(), name="delete"),
    path("update/<int:prod_id>", product_update, name="update"),
    path("api/", products),

]

shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from products.views.views_func import welcome
from django.conf import settings
from django.conf.urls.static import static
from products.views.views_class import AboutView
from django.views.generic.base import TemplateView
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", welcome),
    path("products/", include("products.urls")),
    path("api/products/", include("products.urls_api")),
    path("accounts/", include("accounts.urls")),
    # path("about/", TemplateView.as_view(template_name="about.html",
    #      extra_context={'title': "from path"}))
    path("about/<int:test>/<str:name>", AboutView.as_view()),
    # re_path(r"/*/", TemplateView.as_view(template_name="404.html"))
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns = urlpatterns + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "SHOP"

templates/partials/_nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/products/">{{title}}</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'products:create' %}"
            >Create Product</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <div>
        {% if user.is_authenticated %}
        <span>Welcom: {{user.email}}</span>
        <a class="btn btn-danger" href="{% url 'accounts:logout' %}">Logout</a>
        {% else%}
        <a class="btn btn-primary" href="{% url 'accounts:login' %}">Login</a>
        <a class="btn btn-secondary" href="{% url 'accounts:register' %}"
          >Register</a
        >
        {% endif %}
      </div>
      <form class="d-flex" role="search" action="{% url 'products:list' %}">
        <input
          class="form-control me-2"
          type="search"
          name="q"
          placeholder="Search"
          aria-label="Search"
        />
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>