products/urls.py
from django.urls import path
from products.views.views_func import (
    create_product,
    list_products,
    product_detail,
    product_delete,
    product_update,
)
from products.views.views_class import (
    ListProductView,
    CreatProductView,
    ProductListView,
    ProductCreateView,
    ProductDetailView,
    ProductUpdateView,
    ProductDeleteView
)
from products.views.api import products

app_name = 'products'

urlpatterns = [
    path("", list_products, name="list"),
    path("create/", ProductCreateView.as_view(), name="create"),
    path("detail/<int:prod_id>/",
         product_detail, name="detail"),
    path("delete/<int:prod_id>", ProductDeleteView.as_view(), name="delete"),
    path("update/<int:prod_id>", product_update, name="update"),
    path("api/", products),

]

shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from products.views.views_func import welcome
from django.conf import settings
from django.conf.urls.static import static
from products.views.views_class import AboutView
from django.views.generic.base import TemplateView
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", welcome),
    path("products/", include("products.urls")),
    path("api/products/", include("products.urls_api")),
    path("accounts/", include("accounts.urls")),
    # path("about/", TemplateView.as_view(template_name="about.html",
    #      extra_context={'title': "from path"}))
    path("about/<int:test>/<str:name>", AboutView.as_view()),
    # re_path(r"/*/", TemplateView.as_view(template_name="404.html"))
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns = urlpatterns + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "SHOP"

products/models.py
import random
from django.db import models
from django.forms import ValidationError
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify
from utility.slugHelper import unique_slug_generator
import os
from shop import settings
from django.urls import reverse_lazy


class Category(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        db_table = "category"

    def __str__(self):
        return self.name


class ProductModalManger(models.Manager):
    # def all(self):
    #     return self.filter(is_available=True)

    def is_available(self):
        return self.filter(is_available=True)


# Create your models here.
CATEGORIES = (
    ("ph", 'Phone'),
    ("cm", 'Camera')
)


def price_gt_500(value):
    if value < 500:
        raise ValidationError("Please enter above 500.")


def file(instance, filename):
    print(filename)
    ext = filename.split(".")[1]
    return f"products/{random.randint(1,99999)}.{ext}"


def image_validator(image):
    # if (image.size > 20000):
    #     raise ValidationError("Image must be less than 20KB.")
    pass


class Product(models.Model):
    title = models.CharField(max_length=150, unique=True, error_messages={
        "unique": "No Duplicates.",
        "null": "please fill the input"
    }, help_text="Please enter a unique value.",)
    slug = models.SlugField(null=True, blank=True)
    price = models.IntegerField(validators=[price_gt_500])
    # binray = models.BinaryField(max_length=20, null=True, editable=True)
    is_available = models.BooleanField(default=True)
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, related_name="products")
    image = models.ImageField(
        upload_to=file, null=True, blank=True, validators=[image_validator])
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    db = ProductModalManger()
    objects = ProductModalManger()

    @property
    def tax(self):
        return self.price * 0.1

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy("products:detail", args=[self.id])

    def delete(self, *args, **kwargs):
        # if os.path.exists(self.image.path):
        #     os.remove(self.image.path)
        self.image.delete()
        return super().delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.price = int(self.price)
        if not self.id:
            self.price = self.price + self.price * 0.02
        print("Save Called")
        return super().save(*args, **kwargs)

    class Meta:
        db_table = "product"
        # managed = False
        # abstract = False


# def pre_save_product_signal(sender, instance, *arg, **kwargs):
#     print("Product pre_save")
#     instance.slug = unique_slug_generator(instance)

#     print(unique_slug_generator(instance))


# pre_save.connect(pre_save_product_signal, sender=Product)

def post_save_product_signal(sender, instance, created, *arg, **kwargs):
    print("Product post_save")
    if created:
        instance.slug = unique_slug_generator(instance)
        instance.save()


post_save.connect(post_save_product_signal, sender=Product)

products/forms.py
from products.models import Product
from django import forms
from django.forms import ValidationError


def test_vali(val):
    if not val.startswith("A"):
        raise ValidationError("Name should start with A.")


class TestForm(forms.Form):
    name = forms.CharField(help_text="Name should start with A.", label="Name 1", max_length=5,
                           validators=[test_vali])
    age = forms.IntegerField()


class ProductModalForm(forms.ModelForm):
    class Meta:
        model = Product
        # fields = ['title', 'price', "category"]
        # fields = '__all__'
        exclude = ['slug']

products/views/api.py
from rest_framework.decorators import api_view, APIView
from rest_framework.response import Response
from products.models import Product
from rest_framework.viewsets import ModelViewSet
from products.serializers.products_serializers import TestSerializer, ProductListSerializer
from rest_framework.permissions import AllowAny, IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework import status


@api_view(["GET", 'POST'])
def products(request):
    if request.method == 'GET':
        products = Product.objects.all()
        serilizer = ProductListSerializer(products, many=True)
        print(serilizer.data)
        return Response(serilizer.data, status=status.HTTP_404_NOT_FOUND)
    elif request.method == "POST":
        serilizer = ProductListSerializer(data=request.data)
        if serilizer.is_valid():
            res = serilizer.save()
            return Response(ProductListSerializer(res).data)
        else:
            return Response(serilizer.errors)


class Products(APIView):
    def get(self, request):
        products = Product.objects.all()
        serilizer = ProductListSerializer(products, many=True)
        print(serilizer.data)
        return Response(serilizer.data)

    def post(self, request):
        serilizer = ProductListSerializer(data=request.data)
        if serilizer.is_valid():
            res = serilizer.save()
            return Response(ProductListSerializer(res).data)
        else:
            return Response(serilizer.errors)


@api_view(["POST"])
def test(request):
    print(request.data)
    ser = TestSerializer(data=request.data)
    if ser.is_valid():
        return Response(ser.validated_data)
    else:
        return Response(ser.errors)


class ProductModalViewSet(ModelViewSet):
    queryset = Product.objects.filter(price__gt=4000)
    serializer_class = ProductListSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]

products/views/views_class.py
from products.forms import ProductModalForm
from django.shortcuts import render,  redirect
from django.urls import reverse_lazy
from django.views.generic.base import View
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView


from products.models import Product, Category


class AboutView(View):
    def get(self, request, **kwargs):
        print(kwargs)
        # form = TestForm(initial={'name': 'Test', "age": 34})
        form = ProductModalForm()
        return render(request, 'index.html', {"form": form, **kwargs})

    def post(self, request):
        # form = TestForm(request.POST)
        form = ProductModalForm(request.POST, request.FILES)
        if form.is_valid():
            res = form.save()
            return redirect(reverse_lazy("products:detail", args=[res.id]))
        else:
            print(form.errors)
            return render(request, 'about.html', {"form": form})


class ProductListView(ListView):
    model = Product
    queryset = Product.objects.all()
    template_name = 'products/list_products.html'
    context_object_name = 'products'


class ProductCreateView(CreateView):
    model = Product
    queryset = Product.objects.all()
    fields = "__all__"
    template_name = 'products/create_product.html'


class ListProductView(View):
    def get(self, request, *args, **kwargs):
        print(dict(request.session))
        # products = Product.db.is_available()
        categories = Category.objects.all()
        return render(request, "products/list_products.html", {"categories": categories})


class CreatProductView(View):
    def get(self, request):
        return render(request, "products/create_product.html")

    def post(self, request):
        title = request.POST.get("title")
        price = request.POST.get("price")
        is_available = request.POST.get("is_available")
        product = Product.objects.create(title=title, price=price,
                                         is_available=bool(is_available))
        return render(request, "products/create_product.html", {"id": product.id})


class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/product-detail.html'
    pk_url_kwarg = 'prod_id'


class ProductUpdateView(UpdateView):
    model = Product
    # fields = '__all__'
    fields = ['title', 'price']
    pk_url_kwarg = 'prod_id'
    template_name = 'products/product_update.html'


class ProductDeleteView(DeleteView):
    model = Product
    pk_url_kwarg = 'prod_id'
    success_url = reverse_lazy("products:list")

products/views/views_func.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import Http404, JsonResponse
from django.contrib.auth.decorators import login_required

from products.models import Product

# Create your views here.


def welcome(request):
    return redirect(reverse_lazy("products:list"))


def create_product(request):
    if request.method == 'GET':
        return render(request, "products/create_product.html")
    else:
        title = request.POST.get("title")
        price = request.POST.get("price")
        is_available = request.POST.get("is_available")
        product = Product.objects.create(title=title, price=price,
                                         is_available=bool(is_available))
        return render(request, "products/create_product.html", {"id": product.id})


# @login_required
def list_products(request):
    # print(dir(request))
    search_term = request.GET.get("q")
    if search_term:
        products = Product.db.filter(title__icontains=search_term)
    else:
        products = Product.db.all()

    return render(request, "products/list_products.html", {"products": products})


def product_detail(request, prod_id):
    try:
        product = Product.objects.get(id=prod_id)
    except Product.DoesNotExist:
        raise Http404()
        # return render(request, '404.html', {'P_not_found': True})
    # except Product.MultipleObjectsReturned
    # product = get_object_or_404(Product, id=prod_id)
    print(product.tax)
    return render(request, 'products/product-detail.html', {"product": product})


def product_delete(request, prod_id):
    product = Product.objects.get(id=prod_id)
    product.delete()

    return redirect(reverse_lazy("products:list"))


def product_update(request, prod_id):
    product = Product.objects.get(id=prod_id)
    if request.method == 'GET':
        return render(request, 'products/product_update.html', {"product": product})
    else:
        title = request.POST.get("title")
        price = request.POST.get("price")
        is_avaliable = request.POST.get("is_avaliable")
        desc = request.POST.get("desc")

        product.title = title
        product.price = price
        product.is_available = bool(is_avaliable)
        product.description = desc

        product.save()
        messages.warning(
            request, f"Product with id {prod_id} has been updated successfuly.")
        return redirect(reverse_lazy("products:update", args=[product.id]))

templates/products/create_product.html
{% extends 'base.html' %} {% block content %}

<div style="display: flex; justify-content: center">
  <form
    action="{% url 'products:create' %}"
    method="post"
    style="width: 300px"
    enctype="multipart/form-data"
  >
    {% csrf_token %} {{form.as_div}}
    <button type="submit" class="btn btn-primary">Create Product</button>
  </form>
</div>

{% endblock %}

templates/products/list_products.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div style="display: flex; flex-wrap: wrap; justify-content: center">
  {% for product in products %}
  <div class="card" style="min-width: 250px; margin: 1rem">
    {% if product.image %}
    <img
      src="{{product.image.url}}"
      class="card-img-top"
      alt="..."
      height="150px"
    />
    {% else %}
    <img
      src="{% static 'img/default.png'%}"
      class="card-img-top"
      alt="..."
      height="150px"
    />
    {% endif %}
    <div class="card-body">
      <h5 class="card-title {% cycle 'success' 'warning' 'error' %}">{{product.title}}</h5>
      <p class="card-text">Price: {{product.price}}$</p>
      <p class="card-text">Is Available: {{product.is_available}}</p>

      <p class="card-text">Category: {{product.category}}</p>
      <p class="card-text">Created On: {{product.created|date:"Y-m-d"}}</p>
     
      <a href="{% url 'products:detail' product.id %}" class="btn btn-primary"
        >View more</a
      >
      <!-- <a href="{% url 'products:delete' product.id %}" class="btn btn-danger"
        >Delete</a
      > -->
      <form action="{% url 'products:delete' product.id %}" method="post">{% csrf_token %}
        {{ form }}
        <input type="submit" class="btn btn-danger" value="Delete">
      </form>
    
      <a href="{% url 'products:update' product.id %}" class="btn btn-info"
        >Update</a
      >
    </div>
  </div>
  {% empty %}
  <p>There is not records available.</p>
  {% endfor %}
</div>

{% endblock %}

templates/products/product-detail.html
{% extends 'base.html' %} {% block content %}

<div>
  <h1>Title: {{product.title}}</h1>
  <p>Price: {{product.price}}$</p>
  <p>Is Available: {{product.is_available}}</p>
  <p>Description: {{product.description}}</p>
  <p>Tax: {{product.tax}}</p>
</div>

{% endblock content %}

templates/products/product_update.html
{% extends 'base.html' %} {% block content %}

<div style="display: flex; justify-content: center">
  <form method="post" style="width: 300px">
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Title</label>
      <input
        type="text"
        name="title"
        class="form-control"
        id="exampleInputEmail1"
        value="{{product.title}}"
      />
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Price</label>
      <input
        type="number"
        class="form-control"
        name="price"
        value="{{product.price}}"
      />
    </div>
    <div class="mb-3 form-check">
      <input
        type="checkbox"
        class="form-check-input"
        name="is_avaliable"
        id="exampleCheck1"
        {% if product.is_available %}
        checked
        {% endif %}
      />
      <label class="form-check-label" for="exampleCheck1">Is Avaliable</label>
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Description</label>
      <textarea
        class="form-control"
        name="desc"
        value="{{product.price}}"
      >{{product.description}}</textarea>
    </div>
    <!-- {{form.as_div}} -->
    <button type="submit" class="btn btn-primary">Update Product</button>
  </form>
</div>

{% endblock %}

templates/products/welcome.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1 style="color: red">Welcome to Django</h1>
    <p>{{result}} - {{test}}</p>
    <p>user: {{request.user}}</p>
  </body>
</html>